spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # Default to dev
  application:
    name: cep-service

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.br.cepservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
