spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/cepdb
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate.ddl-auto: validate
    show-sql: false

app:
  external-cep-api:
    base-url: https://brasilapi.com.br/api/cep/v1

aws:
  dynamodb:
    endpoint: https://dynamodb.${AWS_REGION:us-east-1}.amazonaws.com
    region: ${AWS_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}