spring:
  datasource:
    # Disable traditional datasource in production as we're using DynamoDB
    url: ${SPRING_DATASOURCE_URL:none}
    username: ${SPRING_DATASOURCE_USERNAME:none}
    password: ${SPRING_DATASOURCE_PASSWORD:none}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1
  jpa:
    hibernate.ddl-auto: none
    show-sql: false

  # Disable JPA repositories in production
  data:
    jpa:
      repositories:
        enabled: false

app:
  external-cep-api:
    base-url: https://brasilapi.com.br/api/cep/v1
  # Enable rate limiting in production
  rate-limiter:
    enabled: true
    limit: 100
    duration: 60 # seconds
  # API key security configuration
  security:
    api-keys: ${API_KEYS:default-api-key-for-dev}

# AWS Configuration
aws:
  # DynamoDB Configuration
  dynamodb:
    enabled: true
    endpoint: https://dynamodb.${AWS_REGION:us-east-1}.amazonaws.com
    region: ${AWS_REGION:us-east-1}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    table-name: ${DYNAMODB_TABLE_NAME:cep-logs}
    # Performance configuration
    provisioned-throughput:
      read-capacity-units: 5
      write-capacity-units: 5
    # Auto-scaling configuration
    auto-scaling:
      enabled: true
      min-capacity: 5
      max-capacity: 20
      target-utilization: 70

  # Lambda Configuration
  lambda:
    memory: 512
    timeout: 30
    environment: prod

